### PR TITLE
slot: generate __unicode__ name when save()

### PR DESCRIPTION
**Pull request by miurahr**
implement of  #32 

Signed-off-by: Hiroshi Miura <miurahr@linux.com>

### CODE REVIEW

**Comment by paltman** [comment]
@miurahr this seems to conflict with the other one you did (#110) that I just merged.

**Comment by miurahr** [comment]
This may conflict with #100 because #100 changes `__unicode__()` to `__str__()` with `@python_2_unicode_compatible` annotation.

**Comment by miurahr** [comment]
rebased.

**Comment by ossanna16** [comment]
@paltman Can this be merged or is there still a conflict?

**Pull request merged**
